### ISSUE TITLE
I have to import components in isolation if I use a different router.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#103]
In a NextJS application one can't import components like so:

```
import { Button, Header } from "@allenai/varnish/components"
```

This fails as the `react-router-dom` dependency isn't installed (which the various link related components depend upon).

I can workaround this for now by importing them individually:

```
import { Header } from "@allenai/varnish/components/Header";
import { Button } from "@allenai/varnish/components/Button";
```

That said this is a bit of a pain.

**Comment by jonborchardt** [comment]
im not sure there is work to be done here with the fork
