### ISSUE TITLE
Investigate parcel as a replacement for webpack.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#146]
I think we'd benefit from evaluating build systems other than webpack.

I'd love to see us investigate `parcel`. In experimenting with it I liked that it:

* Worked out of the box, with minimal configuration
* Seemed a lot faster
* Uses the HTML file as an entry point, rather than the JavaScript entry, which seems like an accurate choice for web applications (this would make less sense for server-side JS)

If adopted we should use this in the skiff-template as well instead of `webpack`.

**Comment by jonborchardt** [comment]
not after fork
