### ISSUE TITLE
Let's come up with a naming scheme for z-indices.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#153]
We should come up with a naming scheme for z-indices / depth. 

For now we're going to preserve the mechanism where each control with a z-index has an index assigned to it by name:

https://github.com/ant-design/ant-design/blob/69b0cc1a10b80c8014c0b2653aa3db37b1c2a76d/components/style/themes/default.less#L267

We, however, would like a naming convention, just as size has `sm`, `lg`, etc, we'd like something similar for depth:

```TypeScript
const zIndex = {
   street: 0,
   house: 10,
   building: 50,
   skyscraper: 100,
   clouds: 1000,
   interstellar: 10000
}
```

**Comment by codeviking** [comment]
@jonborchardt I queued this up in VNext, lmk if you think it should wait longer.

**Comment by Pelagic-sky** [comment]
how many levels are there?

**Comment by codeviking** [comment]
@Pelagic-sky Sky's the limit! (There's not limit, we can have as many as we want).

**Comment by jonborchardt** [comment]
the ai2-web currently uised theme.zindex.backtop-1, -2, -3 to do background layering
i propose we add :
    backgroundL1: 1,
    backgroundL2: 2,
    backgroundL3: 3,
    backgroundL4: 4,
    backgroundL5: 5,
    backgroundL6: 6,
    backgroundL7: 7,
    backgroundL8: 8,
    backgroundL9: 9,
    backgroundL10: 10,

or something similar

**Comment by jonborchardt** [comment]
using ants
