### ISSUE TITLE
I'd expect the left-hand menu items to change color on hover.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#162]
In the design section of the Varnish demo I'd expect the icons for each menu item to change their fill to our link's hover color on hover.

@Pelagic-sky What do you think? (we can review in person if what I'm proposing is unclear).

**Comment by Pelagic-sky** [comment]
That would be nice.

**Comment by jonborchardt** [comment]
sans designer, im going with stock antd for now
