### ISSUE TITLE
We should have a version of ant's component gallery, with the varnish theme applied.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#165]
It seems like this would be a useful endeavor, as it'd demonstrate whether we've effectively modified ant's base skin.

If we deploy a version of their component gallery, and things don't look right, then there's additional `less` we need to write.

**Comment by codeviking** [comment]
This is hopefully relatively straightforward since their component gallery is OSS.

**Comment by DeNeutoy** [comment]
+10 for this feature, the component gallery is what bumped me from playing to actually using skiff/frontend tech. It would also essentially solve #106 if it retained the code snippets 👍

**Comment by jonborchardt** [comment]
done
