### ISSUE TITLE
Including the varnish styles cause non-varnish ant controls to look bad.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#173]
Both @DeNeutoy and @joelgrus ran into an issue where using non `antd` components within the context of `@allenai/varnish` cause display issues.

![image](https://user-images.githubusercontent.com/801451/64819703-bebc4980-d563-11e9-98d4-ee3f2e867b67.png)

In both circumstances sourcing the `antd` css file fixes the issues:

```
import 'antd/dist/antd.css';
```

This isn't ideal, as it indicates that our styles / theme is somehow causing side-effects that cause native `antd` components to render improperly.

We should fix this, as a user should be able to use both`@allenai/varnish` and `antd` components in the same codebase.

**Comment by DeNeutoy** [comment]
![Screen Shot 2019-10-14 at 10 34 49 AM](https://user-images.githubusercontent.com/16001974/66771210-6fbd4900-ee6e-11e9-9e4c-658522965bfc.png)

The varnish theme also causes the antd tooltip arrow to render oddly - i'll just use this as a thread to update when I find things like this.

```
import { Icon, Tooltip } from "antd";
<Tooltip placement="top" title={emailTooltipInfo}>
  <Icon type="info-circle"></Icon>
</Tooltip>
```

**Comment by codeviking** [comment]
@DeNeutoy Will add a screenshot shortly, but there's a regression in the latest Varnish release with slider controls now as well.

We need to prioritize resolving this sooner rather than later, as it's impacting people's demos.

FYI @schmmd @jonborchardt Is there a way we can indicate that this is a high priority issue that we need to resolve? I'm not sure how we're prioritizing Varnish work items.

**Comment by DeNeutoy** [comment]
![image](https://user-images.githubusercontent.com/16001974/68716640-8af8a280-0559-11ea-9f5d-5721c7844c8d.png)

See the slightly offset sliders

**Comment by jonborchardt** [comment]
fixed
