### ISSUE TITLE
antd `Modal`/ `message` components render underneath the varnish `Header`

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/varnish-legacy#184]
https://autocat.staging.apps.allenai.org/

-> click on "What data formats can I use?"
-> the top of the modal is cut off by the Header

Additionally, if you enter anything into the `model name` field and then click submit, an antd message should be visible instructing a user to upload at least the training data, but you can't see it:

https://github.com/allenai/autocat/blob/master/ui/src/components/PackageForm.tsx#L111

I tried styling the Modal using `z-index: big number` and `position: relative`, but neither of these worked. Also, the message component is a function in antd, so it's hard (/not possible) to make a styled component.

I would expect the antd message component to render on top of the Header:

https://ant.design/components/message/

Thanks!

**Comment by DeNeutoy** [comment]
Hmm this is related to https://github.com/allenai/varnish/pull/154/

i'm on Varnish 0.5.5, so I should have those changes, but given the fixes in that PR, setting the z-index using a styled component seems like it should work.

**Comment by codeviking** [comment]
It's probably related to where you're setting the `z-index`.  I'd use the web inspector and traverse through the parents of the modal, until you find another that's positioned (has a `position` property that's not `initial` or `static`).  You'll likely find the problematic `z-index` there that you need to modify to be larger than that of our header.

That said it's also a mistake that in the default theme the header displays above the modal, so we should fix that.

**Comment by jonborchardt** [comment]
fixed
