### ISSUE TITLE
Need varnish treatment for tags asap for leaderboard

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-legacy#194]
We are using the antd tags: https://ant.design/components/tag/

for compatibility with antd (so the user can use varnish they way they do antd), we will preserve the preset tag color names: magenta, red, volcano, orange, gold, lime, green, cyan, blue, geekblue, and purple. and allow user to set a specific color:
![image](https://user-images.githubusercontent.com/8194065/66931454-f860f400-efea-11e9-8cd6-a11c54350e77.png)

but, for the presets, we want to use varnish colors
to do this, we need a background and text color for each preset
WE WILL ASLO NEED A GRAY, not listed above or below...

here is jonb's quick attempt to do this:
```
&.ant-tag-magenta {
    border: none;
    color: ${({theme}) => theme.color.M7};
    background: ${({theme}) => theme.color.M2};
  }
  &.ant-tag-red {
    border: none;
    color: ${({theme}) => theme.color.R7};
    background: ${({theme}) => theme.color.R2};
  }
  &.ant-tag-volcano {
    border: none;
    color: ${({theme}) => theme.color.R5};
    background: ${({theme}) => theme.color.R1};
  }
  &.ant-tag-orange {
    border: none;
    color: ${({theme}) => theme.color.O9};
    background: ${({theme}) => theme.color.O3};
  }
  &.ant-tag-gold {
    border: none;
    color: ${({theme}) => theme.color.O7};
    background: ${({theme}) => theme.color.O2};
  }
  &.ant-tag-lime {
    border: none;
    color: ${({theme}) => theme.color.G5};
    background: ${({theme}) => theme.color.G1};
  }
  &.ant-tag-green {
    border: none;
    color: ${({theme}) => theme.color.G7};
    background: ${({theme}) => theme.color.G2};
  }
  &.ant-tag-cyan {
    border: none;
    color: ${({theme}) => theme.color.T7};
    background: ${({theme}) => theme.color.T2};
  }
  &.ant-tag-blue {
    border: none;
    color: ${({theme}) => theme.color.B6};
    background: ${({theme}) => theme.color.B2};
  }
  &.ant-tag-geekblue {
    border: none;
    color: ${({theme}) => theme.color.B8};
    background: ${({theme}) => theme.color.B3};
  }
  &.ant-tag-purple {
    border: none;
    color: ${({theme}) => theme.color.P7};
    background: ${({theme}) => theme.colorP2};
  }
```

This looks like this:
![image](https://user-images.githubusercontent.com/8194065/66931883-a2408080-efeb-11e9-8b9e-c4594a5ecd4e.png)
NOTE, we also need a grey, not shown above

please let me know a more correct color for text and background of each
they dont need to be existing varnish colors, but that would be nice....

**Comment by Pelagic-sky** [comment]
&.ant-tag-magenta {
    border: none;
    color: ${({theme}) => theme.color.M8};
    background: ${({theme}) => theme.color.M2};
  }
  &.ant-tag-red {
    border: none;
    color: ${({theme}) => theme.color.R8};
    background: ${({theme}) => theme.color.R2};
  }
  &.ant-tag-volcano {
    border: none;
    color: ${({theme}) => theme.color.R8};
    background: ${({theme}) => #FFE5DA};
  }
  &.ant-tag-orange {
    border: none;
    color: ${({theme}) => theme.color.O9};
    background: ${({theme}) => theme.color.O3};
  }
  &.ant-tag-gold {
    border: none;
    color: ${({theme}) => theme.color.O8};
    background: ${({theme}) => theme.color.O2};
  }
  &.ant-tag-lime {
    border: none;
    color: ${({theme}) => theme.color.G7};
    background: ${({theme}) => #D6F7C1};
  }
  &.ant-tag-green {
    border: none;
    color: ${({theme}) => theme.color.G8};
    background: ${({theme}) => theme.color.G2};
  }
  &.ant-tag-cyan {
    border: none;
    color: ${({theme}) => theme.color.T8};
    background: ${({theme}) => theme.color.T2};
  }
  &.ant-tag-blue {
    border: none;
    color: ${({theme}) => theme.color.B7};
    background: ${({theme}) => theme.color.B2};
  }
  &.ant-tag-geekblue {
    border: none;
    color: ${({theme}) => theme.color.B8};
    background: ${({theme}) => #E0EBFF};
  }
  &.ant-tag-purple {
    border: none;
    color: ${({theme}) => theme.color.P8};
    background: ${({theme}) => theme.colorP2};
  }
 &.ant-tag-neutral {
    border: none;
    color: ${({theme}) => theme.color.N8};
    background: ${({theme}) => theme.colorN4};
  }

**Comment by jonborchardt** [comment]
looks good
![image](https://user-images.githubusercontent.com/8194065/67025072-41cc4480-f0ba-11e9-86c1-82b2f7256171.png)

neutral looks bad on grey background, but rest look good
![image](https://user-images.githubusercontent.com/8194065/67025381-c7e88b00-f0ba-11e9-928a-758564e038ea.png)

should we have another neutral for this case?
here is the stock ant neutral
![image](https://user-images.githubusercontent.com/8194065/67025492-ff573780-f0ba-11e9-84e5-ddc7d1eea4db.png)

**Comment by Pelagic-sky** [comment]
I was worried about the neutral. Seems if we want one neutral, the stock
one with the stroke would work the best for most cases.

**Comment by jonborchardt** [comment]
k

**Comment by jonborchardt** [comment]
done
