### ISSUE TITLE
The left sidebar and main content no longer fill available space.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#200]
The left-sidebar and main content (the portions of the page that have a white background) used to fill available space when the content is smaller than the height of the page.

This is no longer the case.  This may have been a regression during the recent `<Layout />` refactoring I committed.

Notice the light-gray on the left below the sidebar, and that the footer takes up more space than it should.

![image](https://user-images.githubusercontent.com/801451/67542788-4ccb3a00-f6a3-11e9-88e8-59424ffb55d5.png)

**Comment by jonborchardt** [comment]
moot, new site
