### ISSUE TITLE
Relax our peer dependencies a bit.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#206]
In a recent update, we mandated that `react`, `react-dom` and other libraries increase from `16.x.x` to `16.y.y`.

I think it'd be ok for us to set this to a fairly wide version for our peer dependencies (by verifying it works, of course).  So, if we're sure it works for all versions of react `16` I think we'd just say `react@^16`.

This would make it easier to update varnish in repos that use it, as you wouldn't have to update other core dependencies.

**Comment by jonborchardt** [comment]
done with fork
