### ISSUE TITLE
Inject the css file, rather than having users include in in their HTML document.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#207]
I think it'd be convenient for certain use cases if we just injected the static CSS file we depend upon.  It'd make updating applications easier, as one wouldn't have to remember to both update the associated package *and* the css file.

This would, of course, be a bit slower.  We should probably allow the end user to disable this and inject it statically if they choose (and indicate it'll be faster).

**Comment by jonborchardt** [comment]
done with fork
