### ISSUE TITLE
We only list 1/2 of the react-router family as a peer dependency.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#208]
We only list `react-router-dom` as a peer dependency, but really we depend on it and `react-router`.

We should note that we depend upon both (unless of course, we remove the dependency re #190).

**Comment by codeviking** [comment]
Nevermind, `react-router` is already included as a dependency.

This is a little odd, and further food for #190.

**Comment by jonborchardt** [comment]
fixed with fork
