### ISSUE TITLE
Build mechanism to allow derived values from theme measurements

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish-legacy#218]
Currently, all spacing values return strings, but that makes it impossible to derive new values from them (e.g. creating multiples of predefined spacing values, subtracting 1px for media query `min-width` vs `max-width`, etc.).

It would be nice to have a function similar to `fromPixels()` that allows users to do something like this:

```
width: ${deriveValue(theme.spacing.md * 2};
```

We'd need to abstract the numbers out of the theme objects and have some way of differentiating between "give me a string with unit" and "give me a number".

**Comment by aaronsarnat** [comment]
From conversation with @codeviking it would also be nice to be able to be able to return values in `px` instead of `rem`.

> we could also provide an `asPixel` function
> so every “unit” could be a `class Unit`
> with methods `asPixel`
> and a default `toString()` that returns a `rem` based value

**Comment by jonborchardt** [comment]
i dont think design wants to do this...
there are very specific spacings and md*2 is not valid....

**Comment by aaronsarnat** [comment]
@jonborchardt We briefly touched on this in our last Enterprise meeting. There were no objections from Nick. Sam seemed to agree that this would be useful in allowing us to extend our theme to support more intricate design while reducing overall number of magic numbers.

**Comment by jonborchardt** [comment]
you can use getPxValue() or getRemValue()
