### ISSUE TITLE
Add a <Rule /> (horizontal line) component

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish-legacy#227]
See horizontal line separating links form legal copy:

![image](https://user-images.githubusercontent.com/8367927/69270921-cd893300-0b88-11ea-91e9-06d346713e48.png)

This will likely come up a lot. Rather than specifying `border-bottom: 1px solid ${someColor};` over an over again, we should consider adding a component that either extends `<hr />` with some params like thickness and color, etc., or a `<div>` container that applies same params via a border style. I think I prefer the `<hr />` as it's more straightforward (and arguably more semantically valid).

---

Some ideas for params:

| Param     | Type                                                                    | Default Value                            |
|-----------|-------------------------------------------------------------------------|------------------------------------------|
| color     | **enum** (of either all or some subset of Varnish color values)             | TBD (probably some N series color value) |
| thickness | **enum** (of predefined thicknesses)                                        | `'hairline'` (0.0625rem = 1px)             |
| maxWidth  | **`'auto'`** `or` **enum** (of breakpoint values) `or` **number** (to be converted to rems) | `'auto'` (100%)                            |
| margin    | **enum** (of Varnish spacing values)                                        | `'lg'` (24px = 1.5rem)                     |

**Comment by aaronsarnat** [comment]
Per @jonborchardt suggestion, this component could also be based off of Ant's `Divider`:

https://ant.design/components/divider/

**Comment by jonborchardt** [comment]
using ants divider
