### ISSUE TITLE
Figure out how to update antd icons.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#235]
Right now we can add custom icons, and use them instead of using the default icons bundled in by `antd`.  That said this isn't great, as:

* If our end users use the `Icon` component directly, they won't use our "updated" version
* We bundle in both code for the original icon from `antd` and our local version, which causes clients of our sites to download more stuff

It looks like `antd` sources it's icons from this repository: https://github.com/ant-design/ant-design-icons

Maybe we can fork that repo, and somehow wire it in as an icon replacement?  That way we could use @Pelagic-sky's sweet icons without modifying or wrapping the `antd` API.

**Comment by jonborchardt** [comment]
the fork should fix this
