### ISSUE TITLE
lint:fix on button.tsx causes Cloud Build failure

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish-legacy#241]
During a routine update to Varnish, I ran `yarn run lint:fix` before merging, and noticed that `button.tsx` was being modified. I committed the modification, and it caused a build failure so I reverted to the version that is currently in master.

It appears that linting any further changes will result in this same build failure (and the need to revert changes to this file) until this issue can be addressed.

![image](https://user-images.githubusercontent.com/8367927/70666964-9e645f80-1c24-11ea-9960-8f5aca817995.png)

**Comment by aaronsarnat** [comment]
From MichaelL:
>did eslint or its rules get updated in your repo recently?

**Comment by jonborchardt** [comment]
moot, file gone
