### ISSUE TITLE
Button attribute "variant" is getting printed to the DOM but is an invalid html attribute

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish-legacy#242]
![image](https://user-images.githubusercontent.com/8367927/70749698-bb129d00-1ce1-11ea-9a9d-4ae11b8e4e8b.png)

---

From W3C Validator:

![image](https://user-images.githubusercontent.com/8367927/70750575-81429600-1ce3-11ea-8038-5610b2c7c7f0.png)

---

Note this is happening on both `<button>` and `<a>` versions of this component.

**Comment by aaronsarnat** [comment]
Possible fix. See:

- https://github.com/allenai/ai2-web/blob/master/ui/lib/components/containers/Container.tsx#L121
- https://github.com/styled-components/styled-components/issues/135

**Comment by jonborchardt** [comment]
only using antd types now
