### ISSUE TITLE
Varnish components shouldn't import from the top-level.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#254]
When we do this in Varnish components:

```
import { SomeComponent } from '../components'`
```

...it renders the component we've added unusable on projects that don't use `react-router`.

Instead of fixing these on a case by case basis, we should consider not using this pattern.  That said we'll either want to remove the top-level export (delete `components/index.tsx` or find a way to enforce it via the linter), otherwise it'll just creep back in 🕷 .

**Comment by codeviking** [comment]
This is related to #252 and #190.

**Comment by jonborchardt** [comment]
moot now
