### ISSUE TITLE
Selects don't look quite right when they're small.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#257]
I added a `<Select />` to `ai2-web`, and it looked like this (without any additional styles added by me):

![image](https://user-images.githubusercontent.com/801451/72456344-5bdcf800-3779-11ea-9e8e-c21b3a63b2e0.png)

I also noticed that the `<Select />` interestingly includes some margin below it, which I didn't expect:

![image](https://user-images.githubusercontent.com/801451/72456404-76af6c80-3779-11ea-8128-a19ff3b9b577.png)

These both seem like bugs we should fix.

**Comment by codeviking** [comment]
In `ai2` web here's what fixed it:

```TypeScript

const SelectWithBugFixes = styled(Select)`
    & {
        margin: 0;
        text-transform: none;

        .ant-select-selection__rendered {
            margin-right: ${({ theme }) => theme.spacing.lg};
        }
    }
`;
```

**Comment by jonborchardt** [comment]
fixed
