### ISSUE TITLE
Extend <Button> marketing variant family to support ai2-web use cases

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish-legacy#260]
The current [family of marketing buttons](https://varnish.apps.allenai.org/components/buttons) doesn't go far enough to support our needs on ai2-web:

![image](https://user-images.githubusercontent.com/8367927/72575895-dc3b5000-3882-11ea-8fb5-4ae78049d0fd.png)
![image](https://user-images.githubusercontent.com/8367927/72575904-e2313100-3882-11ea-8a68-8818d76e7d0a.png)
![image](https://user-images.githubusercontent.com/8367927/72575910-ebba9900-3882-11ea-8acb-d1e71a2bd7f6.png)

Related: we may want to repurpose the orange outline marketing button (light background, no contrast) and update it to have a blue outline to satisfy one of the above style needs.

![image](https://user-images.githubusercontent.com/8367927/72576104-8adf9080-3883-11ea-840d-194ca564becb.png)

**Comment by jonborchardt** [comment]
not doing
