### ISSUE TITLE
add mark css to varnish

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish-legacy#68]

**Comment by Pelagic-sky** [comment]
I took a look at the Ant Marks and they look good as is. With our color of course.

**Comment by Pelagic-sky** [comment]
I did some research on this and I could not find a site that alters the default Mark Yellow. I asked some other FE's I know and they said they haven't styled this as well. Looking at our color pallet, I think we might just want to leave this as default as I cannot find a replacement color that would work out better.
