### ISSUE TITLE
Update sites not using Varnish to use it.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish-legacy#74]
This evening we had an issue where we needed to quickly update the AI2 logo (as to fix a misspelling). 

The the Varnish based apps this was relatively intuitive.  For non Varnish applications I had to update each individually.

We should port the following applications to Varnish so this is easier in the future:

* https://github.com/allenai/leaderboard
* https://github.com/allenai/beaker-frontend
* https://github.com/allenai/incubator-web

**Comment by jonborchardt** [comment]
will track elsewhere
