### ISSUE TITLE
Dropdown height should be same as Input

### ISSUE THREAD

**Issue by Pelagic-sky** [allenai/varnish-legacy#94]
Referencing Grover, the dropdown height is 30px while the inputs are at 39. We should have the dropdown be the same size, 39px.

**Comment by Pelagic-sky** [comment]
Beaker is having to fix this a lot with their code since they use fields and dropdowns everywhere.

**Comment by Pelagic-sky** [comment]
@mjlangan @meslater1030 For your reference.

**Comment by jonborchardt** [comment]
done
